(()=>{'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const Q={H1:'조선 민주주의 임시정부 수립키로',H2:'미·소 공동위원회 설치, 조선 정당·사회단체와 협의',H3:'조선 신탁통치 협정, 최장 5년 한도로 논의키로',H4:'조선, 5년간 4개국 신탁통치 실시 확정'};
const P=new URLSearchParams(location.search),MODE=P.get('mode')==='paper'?'paper':'standalone',CLASS=(P.get('class')||'미입력').slice(0,40),GAME='newsroom1945',VER='3.4';
const SB='https://xgniwztlrakkrbzcfklb.supabase.co',KEY='sb_publishable_mYZObIGh4nOLKqfnjXHsow_eIARb5U9',SK='1945NEWSROOM_v3_4';
const A={newsroom:'assets/newsroom.webp',meeting:'assets/meeting.webp',press:'assets/press.webp',choi:'assets/choi.webp',yoon:'assets/yoon.webp'};$$('[data-asset]').forEach(x=>x.src=A[x.dataset.asset]);document.body.dataset.mode=MODE;$('#modeBadge').textContent=MODE==='paper'?'학습지 병행':'';
const S={factPick:null,editPick:null,finalPick:null,phase:'#startView',scene1Read:false,scene2Stage:'fact',scene3Stage:1,futureRevealed:false,firstHeadline:'',firstReason:'',factReason:'',editReason:'',reportUSA:'',reportUSSR:'',decisionClaim:'',difference:'',finalDecision:'',directHeadline:'',finalHeadline:'',finalReason:'',resultId:'',completedAt:'',submittedAt:'',submitError:''};
function save(){if(MODE!=='standalone')return;try{sessionStorage.setItem(SK,JSON.stringify(S))}catch{}}function load(){if(MODE!=='standalone')return;try{Object.assign(S,JSON.parse(sessionStorage.getItem(SK)||'{}'))}catch{}}
const views=['#startView','#storyView','#dateView','#scene1','#scene2','#scene3','#scene4','#recordView','#endingView'];function show(id,p=0){views.forEach(v=>$(v).hidden=v!==id);$('#progressBar').style.width=p+'%';$('#openDoc').hidden=!['#scene2','#scene3','#scene4','#recordView'].includes(id);S.phase=id;save();scrollTo(0,0)}
const stories={prologue:[['최 편집장','choi','새로 왔다고 했지?'],['최 편집장','choi','마감 전에 하나 맡아보겠나.'],['윤 기자','yoon','조선에 관한 결정문입니다.'],['최 편집장','choi','제목은 잠시 미뤄두게. 먼저 문서가 실제로 무엇을 말하는지부터 확인해보지.']],afterRead:[['최 편집장','choi','좋아. 이제 문서가 무엇을 말하는지는 확인했겠지.'],['최 편집장','choi','그럼 자네라면 이 내용을 어떤 제목으로 전하겠나?']],after1:[['윤 기자','yoon','편집회의에 같은 문서를 두고 네 개의 제목이 올라왔습니다.']],before3:[['윤 기자','yoon','편집장님. 새 기사가 들어왔습니다.'],['최 편집장','choi','좋아. 결정문과 직접 맞대어 보게.']],before4:[['최 편집장','choi','이제 마지막 마감이네.'],['최 편집장','choi','처음 판단을 유지할지, 수정할지 결정하게.']]};let seq=[],si=0,done=()=>{};function story(key,cb){seq=stories[key];si=0;done=cb;show('#storyView',key==='prologue'?5:key==='afterRead'?20:key==='after1'?30:key==='before3'?55:80);renderStory()}function renderStory(){let [w,img,t]=seq[si];$('#storySpeaker').textContent=w;$('#storyText').textContent=t;$('#storyPortraitImg').src=A[img];$('#storyPortraitImg').alt='가상의 '+w}$('#storyNext').onclick=()=>{if(++si<seq.length)renderStory();else done()};
function bind(id,key,cb){let e=$('#'+id);if(!e)return;e.value=S[key]||'';e.oninput=()=>{S[key]=e.value;save();cb&&cb()}}['firstHeadline','firstReason','factReason','editReason','reportUSA','reportUSSR','decisionClaim','difference','directHeadline','finalReason'].forEach(id=>bind(id,id));
function choices(el,ids,fn,direct=false){el.innerHTML='';ids.forEach(id=>{let b=document.createElement('button');b.type='button';b.className='choice';b.dataset.id=id;b.innerHTML=`<span class="tag">${id}</span><span class="headline">${Q[id]}</span>`;b.onclick=()=>fn(id,b);el.append(b)});if(direct){let b=document.createElement('button');b.type='button';b.className='choice';b.dataset.id='DIRECT';b.innerHTML='<span class="tag">직접 작성</span><span class="headline">내가 최종 제목을 직접 작성합니다</span>';b.onclick=()=>fn('DIRECT',b);el.append(b)}}function lock(el,b){$$(`#${el.id} .choice`).forEach(x=>{x.disabled=true;x.classList.toggle('selected',x===b)})}
choices($('#factChoices'),['H1','H2','H3','H4'],(id,b)=>{S.factPick=id;lock($('#factChoices'),b);$('#factPickedText').textContent=id+' · '+Q[id];$('#factEvidence').hidden=false;save()});
choices($('#editChoices'),['H1','H2','H3'],(id,b)=>{S.editPick=id;lock($('#editChoices'),b);$('#editPickedText').textContent=id+' · '+Q[id];$('#editConfirm').hidden=false;save()});
choices($('#finalChoices'),['H1','H2','H3'],(id,b)=>{S.finalPick=id;lock($('#finalChoices'),b);$('#finalPickedText').textContent=id+' · '+Q[id];$('#directHeadlineField').hidden=true;$('#finalConfirm').hidden=false;$('#previewHeadline').textContent=Q[id];save()},true);$('#finalChoices').lastElementChild.onclick=()=>{S.finalPick='DIRECT';let b=$('#finalChoices .choice[data-id="DIRECT"]');lock($('#finalChoices'),b);$('#finalPickedText').textContent='직접 작성';$('#directHeadlineField').hidden=false;$('#finalConfirm').hidden=false;$('#previewHeadline').textContent=S.directHeadline||'내 최종 제목';save()};$('#directHeadline').oninput=()=>{S.directHeadline=$('#directHeadline').value;$('#previewHeadline').textContent=S.directHeadline||'내 최종 제목';save()};
$('#startGame').onclick=()=>story('prologue',()=>show('#scene1',25));$('#scene1ReadDone').onclick=()=>{S.scene1Read=true;save();story('afterRead',()=>{$('#scene1ReadGate').hidden=true;$('#firstDecisionBox').hidden=false;show('#scene1',25)})};$('#s1Done').onclick=()=>{if(MODE==='standalone'&&(!S.firstHeadline.trim()||!S.firstReason.trim())){ $('#s1Validation').textContent='제목과 이유를 모두 작성하세요.';return}story('after1',()=>show('#scene2',50))};
$('#toEditLayer').onclick=()=>{if(MODE==='standalone'&&!S.factReason.trim()){ $('#factValidation').textContent='비교 근거를 적어보세요.';return}S.scene2Stage='edit';$('#factLayer').hidden=true;$('#editLayer').hidden=false;save()};$('#toScene3Bridge').onclick=()=>{if(MODE==='standalone'&&!S.editReason.trim()){ $('#editValidation').textContent='선택 이유를 적어보세요.';return}story('before3',()=>show('#dateView',60))};$('#dateNext').onclick=()=>show('#scene3',75);
function s3(n){S.scene3Stage=n;$('#scene3Step1').hidden=false;$('#scene3Step2').hidden=n<2;$('#scene3Step3').hidden=n<3;save()}$('#scene3Step1Next').onclick=()=>{if(!S.reportUSA.trim()||!S.reportUSSR.trim()){ $('#scene3Step1Validation').textContent='미국과 소련의 내용을 모두 적어보세요.';return}s3(2)};$('#scene3Step2Next').onclick=()=>{if(!S.decisionClaim.trim()){ $('#scene3Step2Validation').textContent='결정문에서 확인되는 내용을 적어보세요.';return}s3(3)};function reveal(){S.futureRevealed=true;$('#futureBlob').hidden=false;$('#scene3Next').hidden=false;save()}$('#revealFuture').onclick=()=>{if(!S.difference.trim()){ $('#scene3Validation').textContent='두 자료의 차이를 적어보세요.';return}reveal()};$('#scene3Check').onchange=e=>{if(e.target.checked)reveal()};$('#toScene4Bridge').onclick=()=>story('before4',()=>{summary();show('#scene4',90)});
function summary(){$('#summaryFirst').textContent=S.firstHeadline||'활동지에 작성한 첫 제목';$('#summaryFact').textContent=S.factPick?S.factPick+' · '+Q[S.factPick]:'—';$('#summaryEdit').textContent=S.editPick?S.editPick+' · '+Q[S.editPick]:'—'};$$('input[name="finalDecision"]').forEach(r=>r.onchange=()=>{S.finalDecision=r.value;save()});function finalTitle(){return S.finalPick==='DIRECT'?S.directHeadline:(Q[S.finalPick]||'')}
function record(){$('#recordFirstHeadline').textContent=S.firstHeadline||'활동지에 작성한 첫 제목';$('#recordFinalHeadline').textContent=finalTitle()||'—';$('#recordDecisionBadge').textContent=S.finalDecision==='수정'?'최종 판단을 수정했습니다':S.finalDecision==='유지'?'처음 판단을 유지했습니다':'최종 판단';$('#recordFactPath').textContent=S.factPick?`처음 선택: ${S.factPick} → 결정문 대조 후 H4 확인`:'결정문과 제목을 비교했습니다.';$('#recordFactReason').textContent=S.factReason||'—';$('#recordDifference').textContent=S.difference||'활동지에 기록';$('#recordFinalReason').textContent=S.finalReason||'활동지에 기록';let rows=[['첫 제목',S.firstHeadline],['첫 이유',S.firstReason],['사실 판단',S.factPick],['사실 근거',S.factReason],['편집 판단',S.editPick],['편집 이유',S.editReason],['보도-미국',S.reportUSA],['보도-소련',S.reportUSSR],['결정문 확인',S.decisionClaim],['차이',S.difference],['최종 판단',S.finalDecision],['최종 근거',S.finalReason]];$('#recordGrid').innerHTML=rows.map(r=>`<div class="record-item"><div class="rlabel">${r[0]}</div><div class="rvalue"></div></div>`).join('');$$('#recordGrid .rvalue').forEach((e,i)=>e.textContent=rows[i][1]||'—')}
$('#finishGame').onclick=()=>{if(MODE==='standalone'&&(!S.finalPick||!S.finalDecision||!S.finalReason.trim()||(S.finalPick==='DIRECT'&&!S.directHeadline.trim()))){$('#finalValidation').textContent='최종 제목·유지/수정·근거를 모두 확인하세요.';return}S.finalHeadline=finalTitle();save();record();show('#recordView',100)};$('#backToScene4').onclick=()=>show('#scene4',90);
function meta(){if(!S.resultId)S.resultId=GAME+'-'+(crypto.randomUUID?crypto.randomUUID():Math.random().toString(36).slice(2));if(!S.completedAt)S.completedAt=new Date().toISOString();save()}function payload(){meta();return{class:CLASS,game:GAME,timestamp:S.completedAt,choices:{version:VER,record_type:'result',result_id:S.resultId,mode:MODE,first_headline:S.firstHeadline,first_reason:S.firstReason,fact_pick:S.factPick,fact_reason:S.factReason,edit_pick:S.editPick,edit_reason:S.editReason,report_usa:S.reportUSA,report_ussr:S.reportUSSR,decision_claim:S.decisionClaim,difference:S.difference,final_decision:S.finalDecision,final_pick:S.finalPick,direct_headline:S.directHeadline,final_headline:S.finalHeadline||finalTitle(),final_reason:S.finalReason},comment:S.finalReason||''}}async function submit(force=false){if(MODE!=='standalone'||(S.submittedAt&&!force))return;let r=await fetch(SB+'/rest/v1/game_results',{method:'POST',headers:{apikey:KEY,'Content-Type':'application/json',Prefer:'return=minimal'},body:JSON.stringify(payload()),keepalive:true});if(!r.ok)throw Error('HTTP '+r.status);S.submittedAt=new Date().toISOString();S.submitError='';save()}
function submitUI(x){$('#retrySubmit').hidden=true;$('#submitStatus').textContent=x==='saving'?'편집 기록을 저장하는 중입니다…':x==='done'?'✓ 편집 기록이 저장되었습니다.':x==='failed'?'기록 저장에 실패했습니다. 인터넷 연결을 확인한 뒤 다시 시도할 수 있습니다.':'';if(x==='failed')$('#retrySubmit').hidden=false}$('#printFinal').onclick=()=>{$('#endingHeadline').textContent=finalTitle()||'최종 1면';show('#endingView',100);if(MODE==='standalone'){submitUI('saving');submit().then(()=>submitUI('done')).catch(()=>{S.submitError='failed';save();submitUI('failed')})}};$('#retrySubmit').onclick=()=>{submitUI('saving');submit(true).then(()=>submitUI('done')).catch(()=>submitUI('failed'))};$('#restart').onclick=()=>{try{sessionStorage.removeItem(SK)}catch{}location.href=location.pathname+location.search};
const dlg=$('#docDialog');function openDoc(){dlg.showModal()}$('#openDoc').onclick=openDoc;['#openDocS2','#openDocS3','#openDocS3Paper'].forEach(s=>{let e=$(s);if(e)e.onclick=openDoc});$('#closeDoc').onclick=()=>dlg.close();$('#dialogCards').innerHTML=$('#mainDocCards').innerHTML;
$('#soundToggle').onclick=()=>{S.sound=!S.sound;$('#soundToggle').textContent=S.sound?'🔊 사운드 ON':'🔇 사운드 OFF';save()};
load();['firstHeadline','firstReason','factReason','editReason','reportUSA','reportUSSR','decisionClaim','difference','directHeadline','finalReason'].forEach(id=>{let e=$('#'+id);if(e)e.value=S[id]||''});if(S.scene1Read){$('#scene1ReadGate').hidden=true;$('#firstDecisionBox').hidden=false}if(S.scene2Stage==='edit'){$('#factLayer').hidden=true;$('#editLayer').hidden=false}if(S.factPick){let b=$(`#factChoices [data-id="${S.factPick}"]`);if(b){lock($('#factChoices'),b);$('#factPickedText').textContent=S.factPick+' · '+Q[S.factPick];$('#factEvidence').hidden=false}}if(S.editPick){let b=$(`#editChoices [data-id="${S.editPick}"]`);if(b){lock($('#editChoices'),b);$('#editPickedText').textContent=S.editPick+' · '+Q[S.editPick];$('#editConfirm').hidden=false}}s3(S.scene3Stage||1);if(S.futureRevealed)reveal();if(S.finalDecision){let r=$(`input[name="finalDecision"][value="${S.finalDecision}"]`);if(r)r.checked=true}let rest=['#scene1','#scene2','#scene3','#scene4','#recordView','#endingView'];if(rest.includes(S.phase)){if(S.phase==='#recordView')record();if(S.phase==='#scene4')summary();show(S.phase,S.phase==='#scene1'?25:S.phase==='#scene2'?50:S.phase==='#scene3'?75:100);if(S.phase==='#endingView')submitUI(S.submittedAt?'done':S.submitError?'failed':'')}else show('#startView',0);
window.__NEWSROOM_TEST__={state:()=>({...S}),payload,submit,mode:MODE,classId:CLASS};
})();
