(()=>{'use strict';
const D=window.DOKDO_DATA,$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const GAME=D.gameId,VER=D.version,PARAMS=new URLSearchParams(location.search),CLASS=(PARAMS.get('class')||'미입력').slice(0,40);
const SB='https://xgniwztlrakkrbzcfklb.supabase.co',KEY='sb_publishable_mYZObIGh4nOLKqfnjXHsow_eIARb5U9',SK='dokdo1905_build_v1';
const defaultState=()=>({
  lens:'한국사',phase:'start',scene:0,vn:true,initialMarked:'',initialJudgment:'',draftHistory:[],
  evidenceSeen:[],openedOptional:[],hintUsed:[],core1905:[],direct1877:false,mapClues:[],ordSelections:[],outsideOneStatus:'',seokdoStatus:'추가 근거 필요',
  seokdoEvidence:[],niitakaParts:[],report1906Selections:[],contextRelation:'',revisionCount:0,revisionChoice:'',boardLinks:[],selectedExhibitSources:[],
  extractedNotes:[],finalPanel:{title:'',body:'',caution:''},resultId:'',completedAt:'',submittedAt:'',submitError:''
});
let S=defaultState();
function load(){try{const x=JSON.parse(sessionStorage.getItem(SK)||'null');if(x&&typeof x==='object')S={...defaultState(),...x,finalPanel:{...defaultState().finalPanel,...(x.finalPanel||{})}}}catch{}}
function save(){try{sessionStorage.setItem(SK,JSON.stringify(S))}catch{}}
function uniqPush(arr,v){if(v&&!arr.includes(v))arr.push(v)}
function seen(id){uniqPush(S.evidenceSeen,id);save();renderSide()}
function addNote(text,tag='메모'){if(!text)return;const k=tag+'|'+text;if(!S.extractedNotes.some(n=>n.k===k))S.extractedNotes.push({k,tag,text});save();renderSide()}
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function sourceName(id){return D.sources[id]?.title||id}
function progress(n){$('#progressFill').style.width=Math.max(0,Math.min(100,(n/8)*100))+'%'}
function showView(id){['#startView','#storyView','#sceneView','#resultView'].forEach(v=>$(v).hidden=v!==id);scrollTo(0,0)}
function renderSide(){const mem=$('#memoPanel'),seenBox=$('#seenPanel');if(!mem||!seenBox)return;
  const notes=[];
  if(S.initialMarked)notes.push(`<div class="memo-item"><b>처음 검수:</b><br>${esc(S.initialMarked)}</div>`);
  if(S.outsideOneStatus)notes.push(`<div class="memo-item"><b>1877 메모:</b><br>${esc(S.outsideOneStatus)}</div>`);
  if(S.seokdoStatus)notes.push(`<div class="memo-item ${S.revisionChoice?'updated':''}"><b>1900 석도 메모:</b><br>${esc(S.seokdoStatus)}</div>`);
  if(S.contextRelation)notes.push(`<div class="memo-item"><b>1904~1905 관계:</b><br>${esc(S.contextRelation)}</div>`);
  mem.innerHTML=notes.join('')||'<span class="small">아직 저장된 메모가 없습니다.</span>';
  seenBox.innerHTML=S.evidenceSeen.length?S.evidenceSeen.map(x=>`<span class="seen-chip">${esc(sourceName(x))}</span>`).join(''):'<span class="small">아직 열람한 자료가 없습니다.</span>';
}
function feedback(msg,warn=false){const f=$('#sceneFeedback');f.className='feedback show'+(warn?' warn':'');f.innerHTML=msg}
function clearFeedback(){const f=$('#sceneFeedback');f.className='feedback';f.textContent=''}
function mission(items){return `<strong>이번 장면에서 끝내야 할 일</strong><ol>${items.map(x=>`<li>${x}</li>`).join('')}</ol>`}
function passport(s){return `<div class="passport"><span>${esc(s.date||'')}</span><span>${esc(s.author||'')}</span><span>${esc(s.type||'')}</span></div>`}
function sourceCard(id,{context=true,link=true}={}){const s=D.sources[id];if(!s)return'';return `<article class="source-card"><h2>${esc(s.title)}</h2>${passport(s)}${context&&s.context?`<div class="context"><b>왜 이 자료가 만들어졌나?</b>${esc(s.context)}</div>`:''}<div class="reading">${s.paragraphs?s.paragraphs.map(p=>`<p>${esc(p)}</p>`).join(''):`<p>${esc(s.body||'')}</p>`}</div>${s.note?`<div class="terms">${esc(s.note)}</div>`:''}${link&&s.sourceUrl?`<div class="source-link"><a href="${s.sourceUrl}" target="_blank" rel="noopener noreferrer">공식 공개 페이지에서 원문·이미지 확인 ↗</a></div>`:''}</article>`}
function openDialog(id){const s=D.sources[id];if(!s)return;seen(id);$('#dialogTitle').textContent=s.title;$('#dialogBody').innerHTML=sourceCard(id);$('#sourceDialog').showModal()}
function archiveCard(id,desc){const opened=S.openedOptional.includes(id);return `<div class="archive-card ${opened?'opened':''}" data-doc="${id}"><h4>${esc(D.sources[id].title)}</h4><p>${esc(desc)}</p><button type="button" data-open="${id}">${opened?'다시 보기':'열람'}</button></div>`}
function bindArchive(onSave){$$('[data-open]').forEach(b=>b.onclick=()=>{const id=b.dataset.open;uniqPush(S.openedOptional,id);seen(id);save();openDialog(id);b.closest('.archive-card')?.classList.add('opened');b.textContent='다시 보기';onSave&&onSave(id)});}
function setSceneMeta(i,title,question,items,nextLabel){S.scene=i;S.phase='scene';save();showView('#sceneView');progress(i+1);$('#sceneIndex').textContent=`SCENE ${i} / 7`;$('#sceneTitle').textContent=title;$('#sceneQuestion').textContent=question;$('#sceneMission').innerHTML=mission(items);$('#sceneNext').textContent=nextLabel;$('#sceneNext').disabled=true;clearFeedback();renderSide()}
function story(key,cb){if(!S.vn){cb();return}const seq=D.vn[key]||[];if(!seq.length){cb();return}showView('#storyView');let i=0;const r=()=>{$('#storySpeaker').textContent=seq[i][0];$('#storyText').textContent=seq[i][1]};r();$('#storyNext').onclick=()=>{i++;if(i<seq.length)r();else cb()}}

function renderS0(){setSceneMeta(0,'검수 보류','이 문장에서 1905년 당시 기록으로 먼저 확인해 보고 싶은 표현은 무엇인가?',['전시 초안에서 검수할 표현을 하나 표시한다.','왜 확인하려는지 연구 목적을 정한다.'],'1905년 당시 결정문을 연다');
  $('#sceneContent').innerHTML=`<article class="source-card"><h2>청소년 전시 초안</h2><div class="passport"><span>게임 속 가공 원고</span><span>역사 사료 아님</span></div><div class="reading">1905년 일본 내각은 독도가 <button class="evidence-btn phrase" data-v="이전부터 일본 영토였음을 확인">이전부터 일본 영토였음을 확인</button>하고 <button class="evidence-btn phrase" data-v="시마네현에 편입했다">시마네현에 편입했다</button>.</div></article><div class="task-card"><h3>연구 목적</h3><div class="two-col"><button class="evidence-btn why" data-v="1905년 당시 문서에 실제로 있는 표현인지 확인">당시 문서에 실제로 있는 표현인지 확인</button><button class="evidence-btn why" data-v="현재 설명과 1905년 당대 문서의 논리를 비교">현재 설명과 1905년 당대 문서 비교</button></div></div>`;
  const check=()=>{$('#sceneNext').disabled=!(S.initialMarked&&S.initialJudgment)};
  $$('.phrase').forEach(b=>b.onclick=()=>{S.initialMarked=b.dataset.v;$$('.phrase').forEach(x=>x.classList.toggle('selected',x===b));save();renderSide();check()});
  $$('.why').forEach(b=>b.onclick=()=>{S.initialJudgment=b.dataset.v;$$('.why').forEach(x=>x.classList.toggle('selected',x===b));save();check()});
  if(S.initialMarked)$$('.phrase').forEach(x=>x.classList.toggle('selected',x.dataset.v===S.initialMarked));
  if(S.initialJudgment)$$('.why').forEach(x=>x.classList.toggle('selected',x.dataset.v===S.initialJudgment));
  check();
  $('#sceneNext').onclick=()=>{if(!S.draftHistory.some(x=>x.stage==='초안'))S.draftHistory.push({stage:'초안',text:`검수 필요: ${S.initialMarked}`});save();renderS1()};
}
function renderS1(){setSceneMeta(1,'1905년 일본 내각 결정','당시 일본 내각은 어떤 논리로 무엇을 결정했을까?',['1905년 내각 결정의 충분한 본문을 읽는다.','판단 근거 구절 1개 이상과 실제 결정 구절 1개를 저장한다.','보조자료는 필요한 경우에만 연다.'],'1905년보다 앞선 기록을 찾아본다');seen('cabinet1905');
  const s=D.sources.cabinet1905;
  $('#sceneContent').innerHTML=sourceCard('cabinet1905')+`<div class="task-card"><h3>본문에서 연구노트로 가져올 구절</h3><div class="task-help">방금 읽은 본문의 구절을 문장 단위로 탭해 저장합니다. 자료 역할은 저장한 뒤 연구노트에서 확인합니다.</div>${s.selectable.map(x=>`<button class="evidence-btn cab" data-id="${x.id}" data-role="${x.role}" data-t="${esc(x.text)}">${esc(x.text)}</button>`).join('')}</div><div class="archive"><h3>더 조사할 수 있는 자료</h3><p class="task-help">전부 열 필요가 없습니다. 지금 질문에 더 필요한 자료만 고르세요.</p><div class="archive-grid">${archiveCard('currentJapan','현재 일본 정부가 1905년을 어떻게 설명하는지 비교합니다.')}${archiveCard('nakai1904','1905년 결정 전에 제출된 개인 청원을 확인합니다.')}${archiveCard('shimane1905','내각 결정 뒤 지방 행정 고시를 확인합니다.')}</div></div>`;
  const selected=new Set(S.core1905);const check1905=()=>{const basis=$$('.cab.selected[data-role="basis"]').length>=1,dec=$$('.cab.selected[data-role="decision"]').length>=1;$('#sceneNext').disabled=!(basis&&dec)};
  $$('.cab').forEach(b=>{if(selected.has(b.dataset.id))b.classList.add('selected');b.onclick=()=>{b.classList.toggle('selected');b.classList.contains('selected')?selected.add(b.dataset.id):selected.delete(b.dataset.id);S.core1905=[...selected];save();check1905();if(!$('#sceneNext').disabled)feedback('서로 다른 기능을 하는 구절을 확보했습니다. 보조자료는 더 필요할 때만 열어도 됩니다.')}});bindArchive();check1905();
  $('#sceneNext').onclick=()=>{S.core1905.forEach(id=>{const x=s.selectable.find(q=>q.id===id);if(x)addNote(x.text,x.role==='decision'?'1905 결정':'1905 판단 근거')});if(!S.draftHistory.some(x=>x.stage==='1905 확인'))S.draftHistory.push({stage:'1905 확인',text:'1905 결정문에서 직접 확인한 근거와 행정 결정을 분리함'});save();story('after1905',renderS2)};
}
function renderS2(){setSceneMeta(2,'1877년 태정관 지령','태정관이 일본과 관계없다고 처리한 “죽도 외 1도”의 두 번째 섬은 무엇을 가리켰을까?',['지령 본문에서 “죽도 외 1도”의 처리 내용을 확인한다.','첨부 지도에서 명칭과 상대 위치 단서를 확인한다.','본문 직접 문구와 지도까지 연결한 식별을 따로 저장한다.'],'1900년 대한제국 기록을 확인한다');seen('dajokan1877');
  $('#sceneContent').innerHTML=sourceCard('dajokan1877')+`<div class="task-card"><h3>1단계 · 본문 직접 문구</h3><button id="direct1877" class="evidence-btn">“죽도 외 1도”가 일본과 관계없다는 취지로 처리하라고 했다.</button></div><div class="map-dev"><span class="dev-badge">DEV PLACEHOLDER · 실제 기죽도약도 크롭으로 교체 필요</span><h3>2단계 · 첨부 지도 단서</h3><p>정식 자산 이용조건이 확인되기 전까지는 위치 상호작용만 검증하는 개발용 도식입니다. 최종 BUILD에서는 공식 원문 이미지 크롭 위에서 같은 단서를 선택해야 합니다.</p><div class="map-canvas" aria-label="기죽도약도 개발용 위치 도식"><button class="island big" data-map="울릉도에 해당하는 큰 섬 표기">큰 섬</button><button class="island small" data-map="그 동남쪽 바다의 작은 섬 표기">작은 섬</button></div><div class="map-note"><a href="https://dokdo.mofa.go.kr/m/kor/pds/part06_view09.jsp" target="_blank" rel="noopener noreferrer">외교부 공개 페이지에서 실제 기죽도약도 보기 ↗</a></div></div><div class="task-card"><h3>3단계 · 식별 메모</h3><button id="identify1877" class="evidence-btn" disabled>본문의 “외 1도”와 첨부 지도의 두 번째 섬을 연결해 현재 독도로 식별하는 근거가 생겼다.</button><button id="hint1877" class="ghost" type="button">지도 읽기 힌트</button></div>`;
  let direct=S.direct1877,map=new Set(S.mapClues||[]);if(direct)$('#direct1877').classList.add('selected');$$('[data-map]').forEach(b=>{if(map.has(b.dataset.map))b.classList.add('selected')});$('#identify1877').disabled=map.size<2;
  $('#direct1877').onclick=e=>{direct=true;S.direct1877=true;e.currentTarget.classList.add('selected');save();ready()};$$('[data-map]').forEach(b=>b.onclick=()=>{b.classList.toggle('selected');b.classList.contains('selected')?map.add(b.dataset.map):map.delete(b.dataset.map);S.mapClues=[...map];save();$('#identify1877').disabled=map.size<2});if(S.outsideOneStatus)$('#identify1877').classList.add('selected');$('#identify1877').onclick=e=>{e.currentTarget.classList.add('selected');S.outsideOneStatus='본문은 “죽도 외 1도”라고 직접 말하고, 첨부 지도까지 연결하면 두 번째 섬의 식별 근거가 생긴다.';addNote('“죽도 외 1도”가 일본과 관계없다는 취지의 처리','1877 직접 문구');addNote('첨부 지도의 명칭·상대 위치까지 연결해 두 번째 섬을 식별','1877 식별');ready()};$('#hint1877').onclick=()=>{uniqPush(S.hintUsed,'1877-map');feedback('힌트: 본문에 적힌 이름 하나만 보지 말고, 지도에서 큰 섬과 그 주변 작은 섬의 상대 위치를 함께 비교하세요.');save()};function ready(){$('#sceneNext').disabled=!(direct&&S.outsideOneStatus)}
  ready();$('#sceneNext').onclick=()=>{if(!S.draftHistory.some(x=>x.stage==='1877 확인'))S.draftHistory.push({stage:'1877 확인',text:S.outsideOneStatus});save();renderS3()};
}
function renderS3(){setSceneMeta(3,'1900년 대한제국 칙령 제41호','칙령이 직접 확인해 주는 것은 무엇이고, “석도=현재 독도”까지 말하려면 무엇이 더 필요할까?',['행정 개편의 맥락과 제1·2조를 읽는다.','행정 변화와 “울릉전도·죽도·석도” 구절을 각각 저장한다.','현재 독도와의 연결은 우선 “추가 근거 필요”로 남긴다.'],'필요한 1904년 자료를 조사한다');seen('ordinance1900');const s=D.sources.ordinance1900;
  $('#sceneContent').innerHTML=sourceCard('ordinance1900')+`<div class="task-card"><h3>본문 구절 저장</h3><div class="task-help">위 본문에서 확인한 문장을 문장 단위로 탭해 연구노트에 옮깁니다.</div>${s.selectable.map(x=>`<button class="evidence-btn ord" data-id="${x.id}" data-role="${x.role}" data-t="${esc(x.text)}">${esc(x.text)}</button>`).join('')}</div><div class="old-memo"><b>현재 연구 메모</b><br>1900년 원문에는 <strong>석도</strong>가 있다. 현재 독도와의 연결은 <strong>추가 근거 필요</strong>로 남긴다.</div>`;
  const sel=new Set(S.ordSelections||[]);$$('.ord').forEach(b=>{if(sel.has(b.dataset.id))b.classList.add('selected');b.onclick=()=>{b.classList.toggle('selected');b.classList.contains('selected')?sel.add(b.dataset.id):sel.delete(b.dataset.id);S.ordSelections=[...sel];save();$('#sceneNext').disabled=!(sel.has('ord-admin')&&sel.has('ord-area'))}});$('#sceneNext').disabled=!(sel.has('ord-admin')&&sel.has('ord-area'));
  $('#sceneNext').onclick=()=>{s.selectable.forEach(x=>{if(sel.has(x.id))addNote(x.text,x.role==='admin'?'1900 행정개편':'1900 관할 구역')});S.seokdoStatus='1900년 원문에는 “석도”가 있다. 현재 독도와의 연결은 추가 근거 필요.';if(!S.draftHistory.some(x=>x.stage==='1900 보류'))S.draftHistory.push({stage:'1900 보류',text:S.seokdoStatus});save();story('after1900',renderS4)};
}
function renderS4(){setSceneMeta(4,'선택 조사: 1904년의 이름과 시대 맥락','1900년의 “석도”와 1905년의 조치를 더 이해하려면 어떤 자료가 필요할까?',['원하는 보조자료만 선택해 조사한다.','니타카 자료를 열었다면 “누가 / 정보가 어디서 왔나 / 어떤 명칭인가”를 분해한다.','1904~1905 자료의 관계 강도를 현재 근거 범위에서 정한다.'],'1906년 후속 기록을 확인한다');
  $('#sceneContent').innerHTML=`<div class="archive"><h3>선택 자료실</h3><p class="task-help">모든 자료를 열 필요가 없습니다. 지금 질문에 필요하다고 생각하는 자료만 조사하세요.</p><div class="archive-grid">${archiveCard('niitaka1904','1904년 무렵 “독도”라는 명칭 사용 정보를 확인합니다.')}${archiveCard('toponymStudy','석도·독도 명칭 연결에 대한 현대 연구 논증을 봅니다.')}${archiveCard('tsushima1904','러일전쟁 중 군사·통신 조사 사실을 확인합니다.')}${archiveCard('timeline1904','청원·해군 조사·내각 결정·고시의 시간 순서를 확인합니다.')}</div></div><div id="niitakaBreakdown" class="task-card" ${S.openedOptional.includes('niitaka1904')?'':'hidden'}><h3>니타카 기록을 세 부분으로 분해</h3><p class="task-help">자료가 “무엇을 직접 보여주는지”를 확인하려면 정보의 주체와 전달 경로를 나눠 보세요.</p><div class="source-select-grid"><button class="evidence-btn npart" data-p="누가 기록했나: 일본 군함 니타카의 행동일지">누가 기록했나<br><b>일본 군함 니타카의 행동일지</b></button><button class="evidence-btn npart" data-p="정보는 어디서 왔나: 울릉도에서 리앙코르드암을 실제로 보았다는 사람에게서 들은 정보">정보는 어디서 왔나<br><b>울릉도에서 들은 정보</b></button><button class="evidence-btn npart" data-p="어떤 명칭인가: 한국인은 리앙코르드암을 독도라고 적는다는 정보">어떤 명칭인가<br><b>한국인은 “독도”라고 적음</b></button></div></div><div class="task-card"><h3>현재 근거로 1904~1905 관계를 어떻게 메모할까?</h3><div class="two-col"><button class="evidence-btn ctx" data-v="직접 원인이라고 주장한다">직접 원인이라고 주장한다</button><button class="evidence-btn ctx" data-v="1905년을 이해하는 시대적 배경 맥락으로 연결한다">배경 맥락으로 연결한다</button><button class="evidence-btn ctx" data-v="현재 자료만으로 관계 강도는 보류한다">관계 강도 보류</button></div></div>`;
  function bindNiitakaParts(){const partSet=new Set(S.niitakaParts||[]);$$('.npart').forEach(b=>{if(partSet.has(b.dataset.p))b.classList.add('selected');b.onclick=()=>{b.classList.toggle('selected');b.classList.contains('selected')?partSet.add(b.dataset.p):partSet.delete(b.dataset.p);S.niitakaParts=[...partSet];save();if(partSet.size===3){uniqPush(S.seokdoEvidence,'1904년 니타카 기록은 일본 군함이 울릉도에서 들은 명칭 정보를 적은 것이며, 그 안에 한국인이 “독도”라고 적는다는 내용이 있다.');addNote('1904년 일본 군함이 울릉도에서 들은 정보로 “한국인은 독도라고 적는다”는 명칭을 기록','1904 명칭');feedback('니타카 자료의 작성 주체·정보 경로·명칭을 분리했습니다. 대한제국의 공식 명명 문서로 바꾸어 읽지 않습니다.')}})}
  bindArchive(id=>{if(id==='niitaka1904'){$('#niitakaBreakdown').hidden=false;bindNiitakaParts()};if(id==='toponymStudy'){uniqPush(S.seokdoEvidence,'현대 지명 연구가 석도와 독도의 표기·발음 관계를 논증한다.');addNote('현대 연구가 석도·독도 지명 관계를 논증','현대 연구')};if(id==='tsushima1904')addNote('1904년 일본 해군이 유선 전신소 설치 적합성을 조사','1904 군사·통신');save()});bindNiitakaParts();
  $$('.ctx').forEach(b=>{if(S.contextRelation===b.dataset.v)b.classList.add('selected');b.onclick=()=>{$$('.ctx').forEach(x=>x.classList.toggle('selected',x===b));S.contextRelation=b.dataset.v;save();$('#sceneNext').disabled=false;if(S.contextRelation.startsWith('직접'))feedback('현재 확보한 자료는 군사·통신 조사와 시간적 맥락을 보여주지만, 이것만으로 편입 결정의 직접 원인을 단일하게 확정하기에는 부족합니다. 다음 장면으로 진행할 수 있지만 이 경고가 연구 기록에 남습니다.',true);else feedback('현재 읽은 범위에 맞춰 관계 강도를 설정했습니다.')}});if(S.contextRelation)$('#sceneNext').disabled=false;
  $('#sceneNext').onclick=()=>story('before1906',renderS5);
}
function renderS5(){setSceneMeta(5,'1906년 후속 기록','1906년 새 자료는 1900년에 보류했던 “석도” 메모를 어떻게 바꾸게 할까?',['심흥택 관련 보고에서 행정 소속 표현과 일본 측 통보를 각각 표시한다.','의정부 지령에서 중앙정부의 대응을 표시한다.','새 근거 트레이를 확인한 뒤 1900년의 옛 메모를 실제로 수정하거나 보류한다.'],'연구 보드에서 자료 관계를 만든다');seen('shim1906');seen('directive1906');
  $('#sceneContent').innerHTML=sourceCard('shim1906')+`<div class="task-card"><h3>심흥택 관련 보고에서 직접 확인</h3><button class="evidence-btn s1906" data-id="affiliation" data-text="‘본군 소속 독도’라는 행정 소속 표현">“본군 소속 독도”</button><button class="evidence-btn s1906" data-id="notice" data-text="일본 관리 일행이 독도가 일본 영지가 되었다는 취지로 통보했다는 보고">일본 측의 편입 통보 내용</button></div>`+sourceCard('directive1906')+`<div class="task-card"><h3>의정부 지령에서 직접 확인</h3><button class="evidence-btn s1906" data-id="reject" data-text="대한제국 중앙정부가 일본의 독도 영지 주장에 동의하지 않았다">일본 영지 주장에 동의하지 않음</button><button class="evidence-btn s1906" data-id="recheck" data-text="대한제국 중앙정부가 독도의 형편과 일본인의 행동을 다시 조사해 보고하라고 지시했다">재조사 지시</button></div><div id="newClueTray" class="clue-tray"></div><div class="old-memo"><b>1900년에 내가 저장한 메모</b><br>${esc(S.draftHistory.find(x=>x.stage==='1900 보류')?.text||'1900년 원문에는 “석도”가 있다. 현재 독도와의 연결은 추가 근거 필요.')}</div><div id="revisionBox" class="task-card"><h3>이전 메모를 어떻게 수정할까?</h3><p class="task-help">위 1906 자료에서 필요한 구절을 먼저 표시하면 수정 버튼이 열립니다.</p><button class="evidence-btn rev" data-v="후속 명칭·행정 기록을 통해 현재 독도와의 연결을 지지하는 근거가 보강되었다." disabled>근거가 보강되었다고 수정</button><button class="evidence-btn rev" data-v="아직 더 확인하고 싶어 판단을 보류한다." disabled>판단을 계속 보류</button></div><div class="locked-note"><b>어떤 선택에도 남는 주의</b><br>1900년 칙령 원문에 실제로 적힌 글자는 여전히 “석도”입니다.</div>`;
  const picks=new Set(S.report1906Selections||[]);function renderTray(){const map={affiliation:'1906 행정 소속: “본군 소속 독도”',notice:'1906 보고: 일본 측 편입 통보 내용',reject:'중앙정부 대응: 일본 영지 주장에 동의하지 않음',recheck:'중앙정부 대응: 재조사 지시'};$('#newClueTray').innerHTML=[...picks].map(id=>`<div class="clue"><b>새 근거</b><br>${esc(map[id])}</div>`).join('')+S.seokdoEvidence.map(x=>`<div class="clue"><b>선택 조사에서 확보</b><br>${esc(x)}</div>`).join('');const ready=picks.has('affiliation')&&picks.has('notice')&&(picks.has('reject')||picks.has('recheck'));$$('.rev').forEach(b=>b.disabled=!ready);if(ready)feedback('1906년의 행정 소속 표현·일본 측 통보·중앙정부 대응을 분리해 확보했습니다. 이제 1900년 메모를 다시 판단하세요.')}
  $$('.s1906').forEach(b=>{if(picks.has(b.dataset.id))b.classList.add('selected');b.onclick=()=>{b.classList.toggle('selected');b.classList.contains('selected')?picks.add(b.dataset.id):picks.delete(b.dataset.id);S.report1906Selections=[...picks];save();renderTray()}});renderTray();
  $$('.rev').forEach(b=>{if(S.revisionChoice===b.dataset.v)b.classList.add('selected');b.onclick=()=>{if(b.disabled)return;$$('.rev').forEach(x=>x.classList.toggle('selected',x===b));const changed=S.revisionChoice!==b.dataset.v;S.revisionChoice=b.dataset.v;if(changed)S.revisionCount+=1;S.seokdoStatus=b.dataset.v+' (단, 1900년 원문 표기는 “석도”)';if(picks.has('affiliation'))addNote('“본군 소속 독도”라는 행정 표현','1906 보고');if(picks.has('notice'))addNote('일본 관리 일행의 독도 편입 통보가 보고됨','1906 보고');if(picks.has('reject'))addNote('대한제국 중앙정부가 일본의 독도 영지 주장에 동의하지 않음','1906 중앙정부 대응');if(picks.has('recheck'))addNote('대한제국 중앙정부가 독도와 일본인 행동의 재조사를 지시','1906 중앙정부 대응');save();renderSide();$('#sceneNext').disabled=false;feedback('새 자료를 보고 1900년에 저장했던 메모를 실제로 수정했습니다. 원문의 “석도” 표기는 그대로 유지됩니다.')}});if(S.revisionChoice)$('#sceneNext').disabled=false;
  $('#sceneNext').onclick=()=>{if(!S.draftHistory.some(x=>x.stage==='1906 수정'))S.draftHistory.push({stage:'1906 수정',text:S.seokdoStatus});save();renderS6()};
}
function boardSourceIds(){return S.evidenceSeen.filter(id=>D.sources[id]);}
function renderS6(){setSceneMeta(6,'연구 보드','내가 실제로 읽은 자료들 사이에는 어떤 관계가 있을까?',['실제 열람 자료 중 최종 전시에 쓸 핵심 사료 2~4개를 고른다.','두 자료를 선택하고 관계 라벨을 붙인다.','관계는 최대 3개만 남긴다.'],'내 연구 메모로 전시 패널을 편집한다');const ids=boardSourceIds();
  const years={'dajokan1877':'1877','ordinance1900':'1900','niitaka1904':'1904','tsushima1904':'1904','nakai1904':'1904','cabinet1905':'1905','shimane1905':'1905','currentJapan':'현재','toponymStudy':'현대','timeline1904':'정리','shim1906':'1906','directive1906':'1906'};
  const byYear=['1877','1900','1904','1905','1906'].map(y=>({y,ids:ids.filter(id=>years[id]===y)}));
  $('#sceneContent').innerHTML=`<div class="board-shell"><h3>내가 실제로 열람한 자료</h3><div class="timeline">${byYear.map(g=>`<div class="year-col"><div class="year">${g.y}</div>${g.ids.map(id=>`<div class="board-source">${esc(sourceName(id))}</div>`).join('')||'<div class="board-source hidden-source">열람 자료 없음</div>'}</div>`).join('')}</div><div class="task-card"><h3>최종 전시 핵심 사료 2~4개</h3><div class="source-select-grid">${ids.map(id=>`<label><input type="checkbox" class="exsrc" value="${id}"> ${esc(sourceName(id))}</label>`).join('')}</div></div><div class="relation-builder"><h3>자료쌍 → 관계 라벨</h3><div class="two-col"><label>자료 A<select id="relA"><option value="">선택</option>${ids.map(id=>`<option value="${id}">${esc(sourceName(id))}</option>`).join('')}</select></label><label>자료 B<select id="relB"><option value="">선택</option>${ids.map(id=>`<option value="${id}">${esc(sourceName(id))}</option>`).join('')}</select></label></div><div class="two-col"><select id="relLabel"><option value="">관계 선택</option><option>보강한다</option><option>긴장한다</option><option>후속 대응이다</option><option>시대적 배경으로 연결된다</option><option>직접 인과로 단정하기 어렵다</option></select><button id="addRel" type="button">관계 추가</button></div><div id="relList" class="relation-list"></div></div></div>`;
  const sel=new Set(S.selectedExhibitSources);$$('.exsrc').forEach(c=>{if(sel.has(c.value))c.checked=true;c.onchange=()=>{c.checked?sel.add(c.value):sel.delete(c.value);if(sel.size>4){c.checked=false;sel.delete(c.value);feedback('핵심 사료는 최대 4개만 선택합니다.',true)}S.selectedExhibitSources=[...sel];save();check()}});
  function renderRels(){const box=$('#relList');box.innerHTML=S.boardLinks.map((r,i)=>`<div class="relation-item">${esc(sourceName(r.a))} → <b>${esc(r.label)}</b> → ${esc(sourceName(r.b))} <button type="button" data-del="${i}">삭제</button></div>`).join('')||'<span class="small">아직 관계가 없습니다.</span>';$$('[data-del]').forEach(b=>b.onclick=()=>{S.boardLinks.splice(+b.dataset.del,1);save();renderRels();check()})}
  $('#addRel').onclick=()=>{const a=$('#relA').value,b=$('#relB').value,label=$('#relLabel').value;if(!a||!b||!label||a===b){feedback('서로 다른 두 자료와 관계 라벨을 선택하세요.',true);return}if(S.boardLinks.length>=3){feedback('핵심 관계는 최대 3개만 남길 수 있습니다.',true);return}S.boardLinks.push({a,b,label});save();renderRels();check()};
  function check(){$('#sceneNext').disabled=!(sel.size>=2&&sel.size<=4&&S.boardLinks.length>=2)}renderRels();check();
  $('#sceneNext').onclick=()=>story('beforeExhibit',renderS7);
}
function memoBlocks(){const blocks=[];S.extractedNotes.forEach((n,i)=>blocks.push({id:'n'+i,label:n.tag,text:n.text}));S.boardLinks.forEach((r,i)=>blocks.push({id:'r'+i,label:'자료 관계',text:`${sourceName(r.a)} — ${r.label} — ${sourceName(r.b)}`}));return blocks}
function renderS7(){setSceneMeta(7,'청소년 전시 패널 편집','내가 실제로 읽고 저장한 근거만으로 어떤 전시문을 만들 수 있을까?',['내가 확보한 메모 블록을 필요한 만큼 골라 본문에 넣는다.','제목과 연결어를 다듬는다.','현재 자료보다 강하게 단정하지 않는 주의 문구를 남긴다.'],'전시 패널을 확정한다');const blocks=memoBlocks();
  $('#sceneContent').innerHTML=`<div class="editor-grid"><section class="block-bank"><h3>내가 실제로 확보한 메모</h3><p class="task-help">미리 작성된 모범답안은 없습니다. 앞 장면에서 내가 저장한 메모만 나옵니다.</p>${blocks.map(b=>`<button type="button" class="block" data-block="${b.id}" data-text="${esc(b.text)}"><b>${esc(b.label)}</b><br>${esc(b.text)}</button>`).join('')}</section><section class="exhibit-form"><label class="field"><span>패널 제목</span><input id="panelTitle" maxlength="80" value="${esc(S.finalPanel.title||'') }" placeholder="전시 패널 제목"></label><label class="field"><span>핵심 설명</span><textarea id="panelBody" rows="9" maxlength="1200" placeholder="왼쪽의 내 메모를 눌러 문장을 구성하세요.">${esc(S.finalPanel.body||'')}</textarea></label><label class="field"><span>표현상 주의</span><textarea id="panelCaution" rows="4" maxlength="500" placeholder="현재 자료로 단정하지 않을 내용을 적어보세요.">${esc(S.finalPanel.caution||'')}</textarea></label></section></div><div id="panelPreview" class="exhibit-preview"></div>`;
  const body=$('#panelBody'),title=$('#panelTitle'),caution=$('#panelCaution');$$('[data-block]').forEach(b=>b.onclick=()=>{const t=b.dataset.text;if(!body.value.includes(t)){body.value+=(body.value?'\n':'')+t;b.classList.add('used');preview()}});[body,title,caution].forEach(e=>e.oninput=preview);
  function preview(){S.finalPanel={title:title.value.trim(),body:body.value.trim(),caution:caution.value.trim()};save();$('#panelPreview').innerHTML=`<h2>${esc(S.finalPanel.title||'제목을 입력하세요')}</h2><p>${esc(S.finalPanel.body||'내 연구 메모를 이용해 핵심 설명을 구성하세요.').replace(/\n/g,'<br>')}</p><div class="evidence-line"><b>핵심 근거</b><br>${S.selectedExhibitSources.map(id=>esc(sourceName(id))).join(' · ')}</div><div class="evidence-line"><b>표현상 주의</b><br>${esc(S.finalPanel.caution||'아직 작성하지 않음')}</div>`;$('#sceneNext').disabled=!(S.finalPanel.title&&S.finalPanel.body&&S.finalPanel.caution)}preview();
  $('#sceneNext').onclick=()=>finish();
}
function finish(){S.completedAt=S.completedAt||new Date().toISOString();S.phase='result';save();showView('#resultView');progress(8);const path=[['처음 검수',S.initialMarked||'—'],['1900년 보류',S.draftHistory.find(x=>x.stage==='1900 보류')?.text||'—'],['1906년 이후',S.revisionChoice||'—']];$('#resultPath').innerHTML=path.map(x=>`<div class="path-card"><strong>${esc(x[0])}</strong>${esc(x[1])}</div>`).join('');$('#finalExhibit').innerHTML=`<h2>${esc(S.finalPanel.title)}</h2><p>${esc(S.finalPanel.body).replace(/\n/g,'<br>')}</p><div class="evidence-line"><b>내가 선택한 핵심 사료</b><br>${S.selectedExhibitSources.map(id=>esc(sourceName(id))).join(' · ')}</div><div class="evidence-line"><b>표현상 주의</b><br>${esc(S.finalPanel.caution)}</div>`;storyEndAndSubmit()}
function storyEndAndSubmit(){const seq=D.vn.ending;if(S.vn&&seq.length&&!$('#finalExhibit').nextElementSibling?.classList.contains('panel')){const extra=document.createElement('div');extra.className='panel';extra.innerHTML=seq.map(x=>`<p><b>${esc(x[0])}</b> ${esc(x[1])}</p>`).join('');$('#finalExhibit').after(extra)}submitResult()}
function resultId(){if(!S.resultId)S.resultId=GAME+'-'+(crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+Math.random().toString(36).slice(2));save();return S.resultId}
function payload(){return{class:CLASS,game:GAME,choices:{result_id:resultId(),version:VER,course_lens:S.lens,evidence_seen:S.evidenceSeen,hint_used:S.hintUsed,revision_count:S.revisionCount,seokdo_status:S.seokdoStatus,context_relation:S.contextRelation,board_links:S.boardLinks,selected_exhibit_sources:S.selectedExhibitSources,completion:'finished'},comment:'',timestamp:S.completedAt||new Date().toISOString()}}
async function submitResult(force=false){if(S.submittedAt&&!force){$('#saveStatus').textContent='✓ 연구 기록이 이미 저장되었습니다.';return}$('#saveStatus').textContent='연구 기록을 저장하는 중입니다…';$('#retrySave').hidden=true;try{const r=await fetch(SB+'/rest/v1/game_results',{method:'POST',headers:{apikey:KEY,'Content-Type':'application/json',Prefer:'return=minimal'},body:JSON.stringify(payload()),keepalive:true});if(!r.ok)throw new Error('HTTP '+r.status);S.submittedAt=new Date().toISOString();S.submitError='';save();$('#saveStatus').textContent='✓ 연구 기록이 저장되었습니다.'}catch(e){S.submitError=String(e);save();$('#saveStatus').textContent='기록 저장에 실패했습니다. 게임 완료에는 영향이 없습니다.';$('#retrySave').hidden=false}}
function start(){S.lens=$('input[name="lens"]:checked')?.value||'한국사';S.phase='scene';save();story('intro',renderS0)}
function restore(){load();$('#vnToggle').setAttribute('aria-pressed',String(S.vn));$('#vnToggle').textContent=S.vn?'대화 ON':'대화 OFF';if(S.phase==='start'){showView('#startView');progress(0);return}if(S.phase==='result'){finish();return}const fn=[renderS0,renderS1,renderS2,renderS3,renderS4,renderS5,renderS6,renderS7][S.scene]||renderS0;fn()}
$('#startBtn').onclick=start;$('#vnToggle').onclick=()=>{S.vn=!S.vn;$('#vnToggle').setAttribute('aria-pressed',String(S.vn));$('#vnToggle').textContent=S.vn?'대화 ON':'대화 OFF';save()};function reset(){if(confirm('현재 연구 기록을 지우고 처음부터 시작할까요?')){sessionStorage.removeItem(SK);S=defaultState();location.reload()}}$('#restartBtn').onclick=reset;$('#playAgain').onclick=reset;$('#retrySave').onclick=()=>submitResult(true);
restore();
})();
